### ISSUE TITLE
GetCapabilities requests return wrong OnlineResource url

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kargo#108]
Found with 
- [ ] MapServer
- [ ] MapProxy

**Comment by cnouguier** [comment]
MapServer: 
- https://mapserver.org/ogc/wms_server.html#changing-the-online-resource-url
- https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-18-04

**Comment by cnouguier** [comment]
Concerning MapProxy, using https://www.express-gateway.io/docs/policies/request-transformer/ seems to fix the issue:
```
      - request-transformer:
          - action:
              headers:
                add:
                  X-Script-Name: "'/wms'"
```

Beware of the quote
