### ISSUE TITLE
Provide a solution to backup mongodb 

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kargo#169]
https://github.com/stefanprodan/mgob looks like a good candidate as it allows to use `rclone` and `slack`
It also supports replica set

**Comment by cnouguier** [comment]
Mgob does the job but we'd like to be able to filter the database to backup. See: https://github.com/stefanprodan/mgob/issues/119

**Comment by cnouguier** [comment]
Still no feedback from mgob. For now we are not very confident with mgob and its future.

**Comment by cnouguier** [comment]
We provide an helper template to do it using k8S : https://github.com/kalisio/kargo/blob/master/charts/common/templates/_db-backup.tpl#L276

It can be used specifying the job in the values.yaml

```
mongodbBackupRestoreCronjob:
  image: bitnami/mongodb:4.4.11-debian-10-r12
  host: apps-mongodb
  rcloneSecret: '{{ .Values.global.rcloneSecret }}'
  remotePath: 'backup:{{ .Release.Namespace }}'
  backupCron: '0 23 * * *'
  restoreTimestamp: '20220308-1034'
```

And instanciate the template using a template file with the following content:

`{{ include "common.mongodb-backup-restore-cronjobs" (dict "context" $ "args" .Values.mongodbBackupRestoreCronjob) }}`
