### ISSUE TITLE
Bad Mapproxy cache configuration

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kargo#237]
The cache mount point `/mnt/cache` is not the correct target. It should be `/var/mapproxy/config/cache`

**Comment by cnouguier** [comment]
Adding the following configuration to the YAML file solves the issue
```
globals:
  cache:
    base_dir: '/mnt/cache'
    lock_dir: '/mnt/cache/locks'
    tile_lock_dir: '/mnt/cache/tile_locks'
```
