### ISSUE TITLE
Provide a share data volume in MapServer

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kargo#65]
The main mapserver.map file should include a share.map file that could be used by an extenal service to share dynamically some data

**Comment by cnouguier** [comment]
This can be done easily by extending the service when needed => it is worth giving an example

**Comment by cnouguier** [comment]
For example:
1. Define the variable: 
```MAPSERVER_EXTENSION=mapserver-extension```
2 Create the file `mapserver-extention.yml` in your worksapce deploy directory and add the following lines:
````
version: '3.5'

services: 
  mapserver:
    volumes:
      - path_to_volume_to_share:path_to_mount_point
```
