### ISSUE TITLE
Disable basic authentication when accessed from the domain

### ISSUE THREAD

**Issue by claustres** [kalisio/kargo#7]
It should be possible to access the data layers from an application hosted on the same domain, e.g. Maputnik accessing the data from TileserverGL.

Could be done using multiple frontends and different backend ports in traefik ?

**Comment by claustres** [comment]
Played with traefik with config like this without success:
```yml
services:
  tileservergl:
    configs:
      - source: tileservergl_conf
        target: /data/config.json
    deploy:
      labels:
        - "traefik.backend=tileservergl"
        - "traefik.docker.network=${DOCKER_NETWORK}"
        - "traefik.enable=true"
        - "traefik.admin.port=80"
        - "traefik.admin.frontend.entryPoints=http,https"
        - "traefik.admin.frontend.auth.basic=${AUTH_USER}:${AUTH_PASSWORD}"
        - "traefik.admin.frontend.rule=Host:tileservergl.${DOMAIN}"
        - "traefik.services.port=80"
        - "traefik.services.frontend.entryPoints=http,https"
        - "traefik.services.frontend.rule=Host:tileservergl.${DOMAIN};Headers:Referer,https://maputnik.${DOMAIN}/"
```

The referrer rule does not seem to be correctly applied and auth is disabled.

Maybe it requires to publish the backend with 2 different ports but this means opening the second port outside the swarm with `--publish` causing a security issue.

Playing with the path like binding authentication to `/admin` path with rewrite break the web app.
