### ISSUE TITLE
Improve Thredds healthcheck

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kargo#77]
When a service crashed (i.e. WCS), the datasets are not reachable although the catalog is reachable

**Comment by cnouguier** [comment]
By default, Kaargo will provide a basic healthcheck (identical to that provided by Unidata). It will be your responsibility to overwrite the health check to reach a dataset defined in your catalog. It is better to choose a dataset exposed by the more services you have.

Define the variable `THREDDS_EXTENSION=thredds-custom`

And the file `thredds-custom.yml` with the following content:

```
version: '3.5'

services: 
  thredds:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/thredds/catalog/<dataset>/catalog.html"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 3m 
```
